/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipproject.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author akhil
 */
public class AccountSettings extends javax.swing.JFrame {

    /**
     * Creates new form AccountSettings
     */
    public AccountSettings() {
        initComponents();
        try
        {
            Class.forName("java.sql.Driver");
            c = DriverManager.getConnection(Utils.URL,Utils.USER,Utils.PASSWORD);
            s = c.createStatement();
        }
        catch (ClassNotFoundException | SQLException e)
        {
            Utils.displayError(e,this);
        }
    }

    Connection c;
    Statement s;
    ResultSet rs;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentPassword = new javax.swing.JPasswordField();
        newPassword = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JCheckBox();
        updatePasswordButton = new javax.swing.JButton();
        deleteAccountButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Current Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("New Password (if you wanna change)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        currentPassword.setBackground(new java.awt.Color(0,0,0,0));
        currentPassword.setForeground(new java.awt.Color(51, 255, 255));
        currentPassword.setEchoChar('*');
        currentPassword.setOpaque(false);
        getContentPane().add(currentPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 128, -1));

        newPassword.setBackground(new java.awt.Color(0,0,0,0));
        newPassword.setForeground(new java.awt.Color(51, 255, 255));
        newPassword.setEchoChar('*');
        newPassword.setOpaque(false);
        getContentPane().add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 104, -1));

        showPassword.setForeground(new java.awt.Color(51, 255, 255));
        showPassword.setText("Show Passwords");
        showPassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showPasswordStateChanged(evt);
            }
        });
        getContentPane().add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        updatePasswordButton.setBackground(new java.awt.Color(0, 0, 0));
        updatePasswordButton.setForeground(new java.awt.Color(51, 255, 255));
        updatePasswordButton.setText(" Update password ");
        updatePasswordButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        updatePasswordButton.setContentAreaFilled(false);
        updatePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updatePasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 156, 31));

        deleteAccountButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteAccountButton.setForeground(new java.awt.Color(51, 255, 255));
        deleteAccountButton.setText(" Delete Account ");
        deleteAccountButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deleteAccountButton.setContentAreaFilled(false);
        deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 137, 31));

        goBackButton.setBackground(new java.awt.Color(0, 0, 0));
        goBackButton.setForeground(new java.awt.Color(51, 255, 255));
        goBackButton.setText(" Go Back ");
        goBackButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        goBackButton.setContentAreaFilled(false);
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(goBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipproject/java/images/all-inside-screen-bg.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordButtonActionPerformed
        String username = LoginForm.loggedInUser;
        String q = "select password from users where username='"+username+"';";
        try
        {
            rs = s.executeQuery(q);
            rs.first();
            String p = new String(currentPassword.getPassword());
            String pw = rs.getString("password");
            p = Utils.encrypt(p);
            if (!p.equals(pw))
            {
                JOptionPane.showMessageDialog(this,"Wrong password!");
                return ;
            }
            
        }
        catch (SQLException e)
        {
            Utils.displayError(e,this);
        }
        String p = new String(newPassword.getPassword());
        p = Utils.encrypt(p);
        q = "update users set password='"+p+"' where username='"+username+"';";
        int n = 0;
        try
        {
            n = s.executeUpdate(q);
        }
        catch (SQLException e)
        {
            Utils.displayError(e,this);
        }
        if (n==0)
        {
           JOptionPane.showMessageDialog(this,"Error occurred trying to change password!");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Password updated successfully");
        }
    }//GEN-LAST:event_updatePasswordButtonActionPerformed

    private void deleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButtonActionPerformed
        String username = LoginForm.loggedInUser;
        String q = "select password from users where username='"+username+"';";
        try
        {
            rs = s.executeQuery(q);
            rs.first();
            String p = new String(currentPassword.getPassword());
            String pw = rs.getString("password");
            p = Utils.encrypt(p);
            if (!p.equals(pw))
            {
                JOptionPane.showMessageDialog(this,"Wrong password!");
                return ;
            }
            
        }
        catch (SQLException e)
        {
            Utils.displayError(e,this);
        }
        q = "delete from users where username=\""+username+"\"";
        int n = 0;
        try
        {
            n = s.executeUpdate(q);
        }
        catch (SQLException e)
        {
            Utils.displayError(e,this);
        }
        if (n==0)
        {
           JOptionPane.showMessageDialog(this,"Error occurred while trying to delete user!");
        }
        else
        {
            JOptionPane.showMessageDialog(this,"User deleted successfully");
        }
        LoginForm.loggedInUser = "";
        LoginForm.isUserAdmin = false;
        LoginForm.isUserAnonymous=false;
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteAccountButtonActionPerformed

    private void showPasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showPasswordStateChanged
        Utils.showPassword(currentPassword,showPassword);
        Utils.showPassword(newPassword, showPassword);
    }//GEN-LAST:event_showPasswordStateChanged

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        new LoggedInForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField currentPassword;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JButton updatePasswordButton;
    // End of variables declaration//GEN-END:variables
}
