/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipproject.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author akhil
 */
public class AccountSettings extends javax.swing.JFrame {

    /**
     * Creates new form AccountSettings
     */
    public AccountSettings() {
        initComponents();
        try
        {
            Class.forName("java.sql.Driver");
            c = DriverManager.getConnection(Utils.URL,Utils.USER,Utils.PASSWORD);
            s = c.createStatement();
        }
        catch (ClassNotFoundException | SQLException e)
        {
            Utils.displayError(e);
        }
    }

    Connection c;
    Statement s;
    ResultSet rs;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentPassword = new javax.swing.JPasswordField();
        newPassword = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JCheckBox();
        updatePasswordButton = new javax.swing.JButton();
        deleteAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Current Password");

        jLabel2.setText("New Password (if you wanna change)");

        currentPassword.setEchoChar('*');

        newPassword.setEchoChar('*');

        showPassword.setText("Show Passwords");
        showPassword.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showPasswordStateChanged(evt);
            }
        });

        updatePasswordButton.setText("Update password");
        updatePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordButtonActionPerformed(evt);
            }
        });

        deleteAccountButton.setText("Delete Account");
        deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentPassword))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(showPassword)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteAccountButton)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(updatePasswordButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePasswordButton)
                    .addComponent(deleteAccountButton))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordButtonActionPerformed
        String username = LoginForm.loggedInUser;
        String q = "select password from users where username='"+username+"';";
        try
        {
            rs = s.executeQuery(q);
            rs.first();
            String p = new String(currentPassword.getPassword());
            String pw = rs.getString("password");
            p = Utils.encrypt(p);
            if (!p.equals(pw))
            {
                JOptionPane.showMessageDialog(null,"Wrong password!");
                return ;
            }
            
        }
        catch (SQLException e)
        {
            Utils.displayError(e);
        }
        String p = new String(newPassword.getPassword());
        p = Utils.encrypt(p);
        q = "update users set password='"+p+"' where username='"+username+"';";
        int n = 0;
        try
        {
            n = s.executeUpdate(q);
        }
        catch (SQLException e)
        {
            Utils.displayError(e);
        }
        if (n==0)
        {
           JOptionPane.showMessageDialog(null,"Error occurred trying to change password!");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Password updated successfully");
        }
    }//GEN-LAST:event_updatePasswordButtonActionPerformed

    private void deleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButtonActionPerformed
        String username = LoginForm.loggedInUser;
        String q = "select password from users where username='"+username+"';";
        try
        {
            rs = s.executeQuery(q);
            rs.first();
            String p = new String(currentPassword.getPassword());
            String pw = rs.getString("password");
            p = Utils.encrypt(p);
            if (!p.equals(pw))
            {
                JOptionPane.showMessageDialog(null,"Wrong password!");
                return ;
            }
            
        }
        catch (SQLException e)
        {
            Utils.displayError(e);
        }
        q = "delete from users where username=\""+username+"\"";
        int n = 0;
        try
        {
            n = s.executeUpdate(q);
        }
        catch (SQLException e)
        {
            Utils.displayError(e);
        }
        if (n==0)
        {
           JOptionPane.showMessageDialog(null,"Error occurred while trying to delete user!");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"User deleted successfully");
        }
        LoginForm.loggedInUser = "";
        LoginForm.isUserAdmin = false;
        LoginForm.isUserAnonymous=false;
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteAccountButtonActionPerformed

    private void showPasswordStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showPasswordStateChanged
        Utils.showPassword(currentPassword,showPassword);
        Utils.showPassword(newPassword, showPassword);
    }//GEN-LAST:event_showPasswordStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField currentPassword;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JButton updatePasswordButton;
    // End of variables declaration//GEN-END:variables
}
