/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipproject.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akhil
 */
public class BuyGamesForm extends javax.swing.JFrame {

    /**
     * Creates new form BuyGamesForm
     */
    public BuyGamesForm() {
        initComponents();
        try
        {
            Class.forName("java.sql.Driver");
            c = DriverManager.getConnection(Utils.URL,Utils.USER,Utils.PASSWORD);
            s = c.createStatement();
        }
        catch (ClassNotFoundException | SQLException e)
        {
            Utils.displayError(e);
        }
        loadItems();
    }

    Connection c;
    Statement s;
    ResultSet rs;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gamesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buyButton.setText("Buy Games");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        gamesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Name", "Stock", "Price"
            }
        ));
        jScrollPane2.setViewportView(gamesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buyButton)
                        .addGap(142, 142, 142)
                        .addComponent(goBackButton)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyButton)
                    .addComponent(goBackButton))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        DefaultTableModel gamesTableModel = (DefaultTableModel) gamesTable.getModel();
        try
        {
            int selectedRow = gamesTable.getSelectedRow();
            int selectedGameSrno = Integer.valueOf(gamesTableModel.getValueAt(selectedRow,0).toString());
            System.out.println(selectedGameSrno);
            rs = s.executeQuery("select * from games where srno="+selectedGameSrno);
            rs.next();
            int srno = rs.getInt("srno");
            String name = rs.getString("name");
            int stock = rs.getInt("stock");
            int price = rs.getInt("price");
            JOptionPane.showMessageDialog(null,"Thank you for purchasing "+name+", "+LoginForm.loggedInUser+"\nAmount to be paid is Rs."+price+"/-");
            stock--;
            if (stock==0)
            {
                int n = s.executeUpdate("delete from games where srno="+selectedGameSrno);
            }
            else
            {
                int n = s.executeUpdate("update games set stock="+stock+" where srno="+srno);
            }
            loadItems();
        }
        catch (NullPointerException | SQLException e)
        {
            Utils.displayError(e);
            return ;
        }
    }//GEN-LAST:event_buyButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        new LoggedInForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed
   
    private void loadItems()
    {
        DefaultTableModel gamesTableModel = (DefaultTableModel) gamesTable.getModel();
        Utils.clearTable(gamesTable);
        try
        {
            rs= s.executeQuery("select * from games");
            while (rs.next())
            {
                int srno = rs.getInt("srno");
                String name = rs.getString("name");
                int stock = rs.getInt("stock");
                int price = rs.getInt("price");
                gamesTableModel.addRow(new Object[] {srno,name,stock,price});
            }
        }
        catch (SQLException e)
        {
            Utils.displayError(e);
            return ;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyGamesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyGamesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyGamesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyGamesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyGamesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JTable gamesTable;
    private javax.swing.JButton goBackButton;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
