/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipproject.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author akhil
 */
public class BuyGamesForm extends javax.swing.JFrame {

    /**
     * Creates new form BuyGamesForm
     */
    public BuyGamesForm() {
        initComponents();
        loadItems();
    }

    private final boolean DEBUG = false;



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        games = new javax.swing.JComboBox<>();
        buyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buyButton.setText("Buy Games");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(games, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(buyButton)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(games, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(buyButton)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        try
        {
            int selectedGameSrno = Integer.valueOf(games.getSelectedItem().toString().split(" ")[0]);
            Class.forName("java.sql.Driver");
            Connection connection = DriverManager.getConnection(Utils.URL,Utils.USER,Utils.PASSWORD);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from games where srno="+selectedGameSrno);
            resultSet.next();
            int srno = resultSet.getInt("srno");
            String name = resultSet.getString("name");
            int stock = resultSet.getInt("stock");
            int price = resultSet.getInt("price");
            JOptionPane.showMessageDialog(null,"Thank you for purchasing "+name+", "+LoginForm.loggedInUser+"\nAmount to be paid is Rs."+price+"/-");
            stock--;
            if (stock==0)
            {
                int n = statement.executeUpdate("delete from games where srno="+selectedGameSrno);
            }
            else
            {
                int n = statement.executeUpdate("update games set stock="+stock+" where srno="+srno);
            }
            loadItems();
        }
           catch (NullPointerException | ClassNotFoundException | SQLException e)
        {
            if (DEBUG)
                e.printStackTrace();
            else
                JOptionPane.showMessageDialog(null,"Error occurred: "+e.getMessage());
            return ;
        }
    }//GEN-LAST:event_buyButtonActionPerformed
   
    private void loadItems()
    {
        games.removeAllItems();
        try
        {
            Class.forName("java.sql.Driver");
            Connection connection = DriverManager.getConnection(Utils.URL,Utils.USER,Utils.PASSWORD);
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select * from games");
            while (resultSet.next())
            {
                int srno = resultSet.getInt("srno");
                String name = resultSet.getString("name");
                int stock = resultSet.getInt("stock");
                int price = resultSet.getInt("price");
                games.addItem(srno+" "+name+" "+stock+" "+price);
            }
        }
           catch (ClassNotFoundException | SQLException e)
        {
            if (DEBUG)
                e.printStackTrace();
            else
                JOptionPane.showMessageDialog(null,"Error occurred: "+e.getMessage());
            return ;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyGamesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyGamesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyGamesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyGamesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyGamesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JComboBox<String> games;
    // End of variables declaration//GEN-END:variables
}
