/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipproject.java;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author akhil
 */
public class LoggedInForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public LoggedInForm() {
        initComponents();
        try
        {
            Class.forName("java.sql.Driver");
            c = DriverManager.getConnection(Utils.URL,Utils.USER,Utils.PASSWORD);
            s = c.createStatement();
        }
        catch (ClassNotFoundException | SQLException e)
        {
            Utils.displayError(e,this);
        }
    }
    
    
    Connection c;
    Statement s;
    public static boolean isAuthorized = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        listAllGamesButton = new javax.swing.JButton();
        inputButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        buyGamesButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        accountSettingsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(51, 255, 255));
        if (!LoginForm.isUserAnonymous)
        {
            welcomeLabel.setText("Welcome to NRK Games, "+LoginForm.loggedInUser);
        }
        else
        {
            welcomeLabel.setText("Welcome to NRK Games, Anonymous User");
        }
        getContentPane().add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 440, -1));

        listAllGamesButton.setBackground(new java.awt.Color(0, 0, 0));
        listAllGamesButton.setForeground(new java.awt.Color(51, 255, 255));
        listAllGamesButton.setText("List of all games");
        listAllGamesButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listAllGamesButton.setContentAreaFilled(false);
        listAllGamesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllGamesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(listAllGamesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 146, 31));

        inputButton.setBackground(new java.awt.Color(0, 0, 0));
        inputButton.setForeground(new java.awt.Color(51, 255, 255));
        inputButton.setText("Insert new entry");
        inputButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputButton.setContentAreaFilled(false);
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });
        getContentPane().add(inputButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, 31));
        if (!LoginForm.isUserAdmin)
        inputButton.setVisible(false);

        deleteButton.setBackground(new java.awt.Color(0, 0, 0));
        deleteButton.setForeground(new java.awt.Color(51, 255, 255));
        deleteButton.setText("Delete an entry");
        deleteButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deleteButton.setContentAreaFilled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 141, 31));
        if (!LoginForm.isUserAdmin)
        deleteButton.setVisible(false);

        buyGamesButton.setBackground(new java.awt.Color(0, 0, 0));
        buyGamesButton.setForeground(new java.awt.Color(51, 255, 255));
        buyGamesButton.setText("Buy Games");
        buyGamesButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buyGamesButton.setContentAreaFilled(false);
        buyGamesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyGamesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buyGamesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 31));
        if (LoginForm.isUserAnonymous)
        buyGamesButton.setVisible(false);

        logoutButton.setBackground(new java.awt.Color(0, 0, 0));
        logoutButton.setForeground(new java.awt.Color(51, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logoutButton.setContentAreaFilled(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 140, 31));

        accountSettingsButton.setBackground(new java.awt.Color(0, 0, 0));
        accountSettingsButton.setForeground(new java.awt.Color(51, 255, 255));
        accountSettingsButton.setText("Account Settings");
        accountSettingsButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        accountSettingsButton.setContentAreaFilled(false);
        accountSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountSettingsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(accountSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 140, 31));
        if (LoginForm.isUserAdmin || LoginForm.isUserAnonymous)
        accountSettingsButton.setVisible(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ipproject/java/images/all-inside-screen-bg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listAllGamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllGamesButtonActionPerformed
        new GamesForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listAllGamesButtonActionPerformed

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed
        new AddNewStuff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inputButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        new DeleteForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void buyGamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyGamesButtonActionPerformed
        new BuyGamesForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buyGamesButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginForm.loggedInUser = "";
        LoginForm.isUserAdmin = false;
        LoginForm.isUserAnonymous=false;
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void accountSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountSettingsButtonActionPerformed
        new AccountSettings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountSettingsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoggedInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoggedInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoggedInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoggedInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoggedInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountSettingsButton;
    private javax.swing.JButton buyGamesButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton inputButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listAllGamesButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
