package ipproject.java;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author akhil
 */
public class LoggedInForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public LoggedInForm() {
        initComponents();
        try
        {
            Class.forName("java.sql.Driver");
            c = DriverManager.getConnection(Utils.URL,Utils.USER,Utils.PASSWORD);
            s = c.createStatement();
        }
        catch (ClassNotFoundException | SQLException e)
        {
            Utils.displayError(e);
        }
    }
    
    
    Connection c;
    Statement s;
    public static boolean isAuthorized = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        listAllGamesButton = new javax.swing.JButton();
        inputButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        buyGamesButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        deleteAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        if (!LoginForm.isUserAnonymous)
        welcomeLabel.setText("Welcome to NRK Games, "+LoginForm.loggedInUser);
        else
        welcomeLabel.setText("Welcome to NRK Games, Anonymous User");

        listAllGamesButton.setText("List of all games");
        listAllGamesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllGamesButtonActionPerformed(evt);
            }
        });

        inputButton.setText("Insert new entry");
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete an entry");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        buyGamesButton.setText("Buy Games");
        buyGamesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyGamesButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        deleteAccountButton.setText("Delete Account");
        deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteAccountButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listAllGamesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputButton)
                        .addGap(18, 18, 18)
                        .addComponent(logoutButton)))
                .addGap(27, 27, 27)
                .addComponent(buyGamesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listAllGamesButton)
                    .addComponent(inputButton)
                    .addComponent(logoutButton)
                    .addComponent(buyGamesButton)
                    .addComponent(deleteButton))
                .addGap(43, 43, 43)
                .addComponent(deleteAccountButton)
                .addGap(36, 36, 36))
        );

        if (!LoginForm.isUserAdmin)
        inputButton.setVisible(false);
        if (!LoginForm.isUserAdmin)
        deleteButton.setVisible(false);
        if (LoginForm.isUserAnonymous)
        buyGamesButton.setVisible(false);
        if (LoginForm.isUserAdmin || LoginForm.isUserAnonymous)
        deleteAccountButton.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listAllGamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllGamesButtonActionPerformed
        new GamesForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listAllGamesButtonActionPerformed

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed
        new AddNewStuff().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_inputButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        new DeleteForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void buyGamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyGamesButtonActionPerformed
        new BuyGamesForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buyGamesButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginForm.loggedInUser = "";
        LoginForm.isUserAdmin = false;
        LoginForm.isUserAnonymous=false;
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void deleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButtonActionPerformed
        String username = LoginForm.loggedInUser;
        String q = "delete from users where username=\""+username+"\"";
        int n = 0;
        try
        {
            n = s.executeUpdate(q);
        }
        catch (SQLException e)
        {
            Utils.displayError(e);
        }
        if (n==0)
        {
           JOptionPane.showMessageDialog(null,"Error occurred while trying to delete user!");
        }
        logoutButton.doClick();
    }//GEN-LAST:event_deleteAccountButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoggedInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoggedInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoggedInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoggedInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoggedInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyGamesButton;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton inputButton;
    private javax.swing.JButton listAllGamesButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
